### ISSUE TITLE
Order Statistic Tree Sizes

### ISSUE THREAD

**Issue by UgurKap** [UgurKap/algorithm-implementations#1]
After deleting a node, some of the nodes seem to have wrong sizes. So, order statistic tree is useless after deleting an element as it is.

So, I have to review what is wrong with delete and transplant functions.

**Comment by AccidentalQuant** [comment]
Line 258 of OrderStatisticTree.cpp should be changed as follows:
/* current */
Node *traverse = temp->parent;

/* Suggested Change */
Node *traverse = temp;

**Comment by UgurKap** [comment]
> Line 258 of OrderStatisticTree.cpp should be changed as follows:
> /* current */
> Node *traverse = temp->parent;
> 
> /* Suggested Change */
> Node *traverse = temp;

Seems to work, thanks.
